# Generated by Django 5.2.8 on 2026-01-07 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID (cus_...)', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID (sub_...)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete (expired)'), ('unpaid', 'Unpaid')], default='trialing', help_text='Current status as reported by Stripe.', max_length=32)),
                ('trial_end', models.DateTimeField(blank=True, help_text='End of free trial period, if any.', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of current billing period.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
