# Generated by Django 5.2.8 on 2026-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_had_trial',
            field=models.BooleanField(default=False, help_text='True if the user has ever started a free trial.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete (expired)'), ('unpaid', 'Unpaid')], default='incomplete', help_text='Current status as reported by Stripe.', max_length=32),
        ),
    ]
