# Generated by Django 5.2.8 on 2026-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_has_had_trial_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='True if the user has cancelled and the subscription will end at period end/trial end.'),
        ),
    ]
