# Generated by Django 5.2.8 on 2026-01-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, help_text='If set, the subscription is scheduled to cancel at this time (UTC).', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='True if Stripe says the subscription will cancel at the end of the current period.'),
        ),
    ]
