# Generated by Django 5.2.8 on 2025-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Emotion word',
                'verbose_name_plural': 'Emotion words',
                'ordering': ['word'],
            },
        ),
    ]
