# Generated by Django 5.2.8 on 2025-12-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emotionword'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(blank=True, null=True)),
                ('hue', models.CharField(blank=True, max_length=7)),
                ('emotion_words', models.CharField(blank=True, help_text='Comma-separated emotion words at the time of this revision.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.entry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
