# Generated by Django 5.2.8 on 2025-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entryrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrevision',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'Very low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very good')], null=True),
        ),
    ]
