# Generated by Django 5.2.8 on 2026-01-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_entryrevision_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='entryrevision',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entry revision', 'verbose_name_plural': 'Entry revisions'},
        ),
    ]
