# Generated by Django 5.2.8 on 2026-01-26 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteannouncement_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrevision',
            name='emotion_words',
            field=models.CharField(blank=True, help_text='Comma-separated emotion words at time of edit.', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(blank=True, help_text='Used if the user is logged out.', max_length=254),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set if the user was logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
