# Generated by Django 5.2.8 on 2026-01-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_entryrevision_emotion_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='emotion_word_tags',
            field=models.ManyToManyField(blank=True, help_text='Relational emotion word tags linked to this entry.', related_name='entries', to='core.emotionword'),
        ),
    ]
